### ISSUE TITLE
On Windows, the page should link to the Windows installer

### ISSUE THREAD

**Issue by RReverser** [wasmerio/wasmer.io#5]
On most websites for binaries with multi-platform support, the main page usually shows shell command for Unix systems and Windows installer if user opened it on Windows.

Right now, opening the website on Windows still shows the shell command, even though there is an official Windows installer for Wasmer on Github releases.

I believe it should be discoverable more easily.

**Comment by syrusakbary** [comment]
I just seen this issue, not sure how I missed it.

But good call!

**Comment by syrusakbary** [comment]
I just fixed this with: https://github.com/wasmerio/wasmer.io/commit/d7d20531a7418916cd75fa1b349ed73e71ee8cc5

Closing issue!
