### ISSUE TITLE
link to spectrum.chat is out of date

### ISSUE THREAD

**Issue by coderedart** [wasmerio/wasmer.io#60]
in https://wasmer.io/community there's a "Ask a Question in the Forum" button which takes you to https://spectrum.chat/wasmer?tab=posts which says "Spectrum is now read-only. Learn more about the decision in our [official announcement](https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5)."

I assume that means the link is supposed to be dead now? if so it can be removed as it is confusing :)

**Comment by syrusakbary** [comment]
Fixed it on master. Thanks for reporting it!
